# Generated by Django 5.1.1 on 2024-12-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyect',
            old_name='technology',
            new_name='nombre_proyecto',
        ),
        migrations.RenameField(
            model_name='proyect',
            old_name='title',
            new_name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='proyect',
            name='description',
        ),
        migrations.AddField(
            model_name='proyect',
            name='rut',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='proyect',
            name='segundo_apellido',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
